spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: inspector
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database: postgresql
